apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-claim
  namespace: local-registry
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
