apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  labels:
    app: registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: 'docker.io/joxit/docker-registry-ui'
          imagePullPolicy: Always
          env:
            - name: REGISTRY_TITLE
              value: 'Docker registry UI'
            - name: DELETE_IMAGES
              value: 'true'
            - name: NGINX_PROXY_PASS_URL
              value: 'http://registry.local-registry:5000'
            - name: PULL_URL
              value: 'localhost:32000'
            - name: SINGLE_REGISTRY
              value: 'true'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
