apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  labels:
    app: registry-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 32080
      protocol: TCP
      name: http
  selector:
    app: registry-ui
