apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: local-registry
  labels:
    app: registry
spec:
  type: NodePort
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
      nodePort: 32000
      protocol: TCP
  selector:
    app: registry
