apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/registry-volume/
