---
- name: install cert-manager on kubernetes cluster
  hosts: local-vm

  tasks:
    - name: create cert-manager namespace
      shell: microk8s kubectl create namespace cert-manager --dry-run=client -o yaml | microk8s kubectl apply -f -
      register: result
    - name: print kubectl logs
      debug:
        msg: '{{ result.stdout }}'

    - name: deploy cert-manager manifest
      shell: microk8s kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.yaml
      register: result
    - name: print kubectl logs
      debug:
        msg: '{{ result.stdout }}'
