apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
  namespace: web
spec:
  dnsNames:
    - 'kubernetes.test'
    # - '*.web.svc.cluster.local'
    # - '*.web'
  secretName: web-cert-tls
  issuerRef:
    name: web
